name: Unit tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.x', '22.x', '24.x']
    name: Node ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn test
      # Make sure tsc compiles
      - run: yarn build
